DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

DROP TABLE IF EXISTS Avatar;

CREATE TABLE Avatar (
  "id"   BIGINT UNIQUE  NULL DEFAULT NULL,
  "name" VARCHAR(50)    NULL DEFAULT NULL
);

DROP TABLE IF EXISTS ADevice;

CREATE TABLE ADevice (
  "id"   BIGINT UNIQUE  NULL DEFAULT NULL,
  "userid" BIGINT NULL DEFAULT NULL,
  "uuid" VARCHAR(50)    NULL DEFAULT NULL
);

DROP TABLE IF EXISTS Purchase;

CREATE TABLE Purchase (
  "id"   BIGINT UNIQUE  NULL DEFAULT NULL,
  "name" VARCHAR(50)    NULL DEFAULT NULL
);